# This file was generated by GoReleaser. DO NOT EDIT.
class Awsctl < Formula
  desc "CLI based tool to help manage AWS profiles for accounts enabled with MFA"
  homepage "https://github.com/outlawlabs/awsctl"
  version "0.5.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/outlawlabs/awsctl/releases/download/v0.5.2/awsctl_Darwin_x86_64.tar.gz"
    sha256 "33eefbeb1fc749827efcbdebb30fc40bd426b52614d5e5e51495b11983a51a95"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/outlawlabs/awsctl/releases/download/v0.5.2/awsctl_Linux_x86_64.tar.gz"
      sha256 "2a97a1e698133191b1529011e7015f87d26018453389b25bb0f061c90e2c170b"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/outlawlabs/awsctl/releases/download/v0.5.2/awsctl_Linux_arm64.tar.gz"
        sha256 "b7fcbed4d2bfc182d3f49571845c281040bcc00a7689f54a251fe9a05f8a6e8f"
      else
      end
    end
  end

  def install
    bin.install "awsctl"
  end

  test do
    system "#{bin}/awsctl --version"
  end
end
